// Conversation modes supplied by the user. Display casing is preserved here.
export const additionalModeNames = [
  "default",
  "Optimist",
  "Pessimist",
  "Realist",
  "Idealist",
  "Pragmatist",
  "Skeptic",
  "Cynic",
  "Critical Thinker",
  "Contrarian",
  "Stoic",
  "Empath",
  "Introvert",
  "Extrovert",
  "Perfectionist",
  "Minimalist",
  "Maximalist",
  "Free Spirit",
  "Rebel",
  "Traditionalist",
  "Futurist",
  "Intellectual",
  "Curious Generalist",
  "Devil's Advocate",
  "FactBot",
  "Storyteller",
  "Comedian",
  "Philosopher",
  "Mentor",
  "Wise Elder",
  "Naive Optimist",
  "Conspiracy Theorist",
  "Doomer",
  "Utopian",
  "Hedonist",
  "Ascetic",
  "Career-Focused Wife",
  "Traditional Housewife with Kids",
  "Working Mother",
  "Single Mother",
  "Stay-at-Home Mother",
  "Childfree Professional Woman",
  "Female Entrepreneur",
  "Female Executive",
  "Female Scientist",
  "Female Engineer",
  "Female Physician",
  "Female Lawyer",
  "Female Politician",
  "Female Journalist",
  "Female Professor",
  "Female Artist",
  "Female Athlete",
  "Female Soldier",
  "Female Police Officer",
  "Female Hacker",
  "Female Gamer",
  "Female Content Creator",
  "Fashion Influencer",
  "Beauty Influencer",
  "Lifestyle Influencer",
  "Feminist Activist",
  "Traditionalist Woman",
  "Socialite",
  "Fashionista",
  "Girl Next Door",
  "High-School Girlfriend",
  "College Girlfriend",
  "Childhood Friend",
  "Best Friend",
  "Older Sister",
  "Younger Sister",
  "Protective Mother",
  "Strict Mother",
  "Grandmother",
  "Wealthy Heiress",
  "Self-Made Millionaire",
  "Corporate Executive",
  "Small-Town Woman",
  "City Professional",
  "Digital Nomad",
  "Backpacker",
  "Sex Worker",
  "Personal Assistant",
  "Executive Assistant",
  "Business Owner",
  "Startup Founder",
  "CEO",
  "COO",
  "CFO",
  "CTO",
  "Product Manager",
  "Project Manager",
  "Operations Manager",
  "HR Manager",
  "Recruiter",
  "Management Consultant",
  "Strategy Consultant",
  "Entrepreneur",
  "Venture Capitalist",
  "Investment Banker",
  "Salesperson",
  "Market Researcher",
  "Marketer",
  "Brand Strategist",
  "Advertiser",
  "Accountant",
  "Auditor",
  "Economist",
  "Personal Finance Expert",
  "Financial Adviser",
  "Insurance Expert",
  "Real Estate Agent",
  "Negotiator",
  "Mediator",
  "Hacker",
  "Ethical Hacker",
  "Security Expert",
  "Cybersecurity Expert",
  "Desktop Programmer",
  "Web Developer",
  "Mobile Developer",
  "Game Developer",
  "System Administrator",
  "DevOps Engineer",
  "Network Engineer",
  "Database Administrator",
  "Software Architect",
  "Computer Scientist",
  "Data Scientist",
  "Data Engineer",
  "AI Expert",
  "AI Safety Researcher",
  "Robotics Engineer",
  "Electronics Engineer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Chemical Engineer",
  "Aerospace Engineer",
  "Physicist",
  "Mathematician",
  "Statistician",
  "Biologist",
  "Chemist",
  "Astronomer",
  "Neuroscientist",
  "Physician",
  "Surgeon",
  "Nurse",
  "Psychiatrist",
  "Psychologist",
  "Therapist",
  "Couples Therapist",
  "Sexologist",
  "Social Worker",
  "Nutritionist",
  "Physiotherapist",
  "Pharmacist",
  "Medical Researcher",
  "Public Health Expert",
  "Alternative Medicine Practitioner",
  "Lawyer",
  "Prosecutor",
  "Defense Attorney",
  "Judge",
  "Police Detective",
  "Criminologist",
  "Political Scientist",
  "Politics Expert",
  "Diplomat",
  "Civil Servant",
  "Mayor",
  "Member of Parliament",
  "President",
  "Prime Minister",
  "Corrupt Politician",
  "Political Strategist",
  "Campaign Manager",
  "Investigative Journalist",
  "Human Rights Advocate",
  "Soldier",
  "Military Officer",
  "General",
  "Military Adviser",
  "Military Historian",
  "Intelligence Analyst",
  "Spy",
  "Double Agent",
  "War Correspondent",
  "Strategist",
  "Logistics Officer",
  "Special Operations Veteran",
  "History Teacher",
  "Philosophy Professor",
  "Literature Professor",
  "Economics Professor",
  "Science Teacher",
  "University Professor",
  "Librarian",
  "Historian",
  "Archaeologist",
  "Anthropologist",
  "Sociologist",
  "Linguist",
  "Political Philosopher",
  "Theologian",
  "Writer",
  "Novelist",
  "Poet",
  "Screenwriter",
  "Journalist",
  "Satirist",
  "Film Director",
  "Actor",
  "Musician",
  "Composer",
  "Painter",
  "Photographer",
  "Graphic Designer",
  "Architect",
  "Fashion Designer",
  "Interior Designer",
  "Content Creator",
  "YouTuber",
  "Streamer",
  "Portuguese Grandmother",
  "Portuguese Café Owner",
  "Lisbon Intellectual",
  "Porto Business Owner",
  "Brazilian Entrepreneur",
  "Brazilian University Student",
  "Mexican Family Matriarch",
  "Argentine Intellectual",
  "American Patriot",
  "American Progressive",
  "British Aristocrat",
  "British Pub Regular",
  "French Intellectual",
  "Parisian Artist",
  "German Engineer",
  "Italian Grandmother",
  "Italian Entrepreneur",
  "Spanish Artist",
  "Scandinavian Minimalist",
  "Eastern European Grandmother",
  "Russian Intellectual",
  "Ukrainian Entrepreneur",
  "Turkish Merchant",
  "Lebanese Entrepreneur",
  "Egyptian Historian",
  "Moroccan Shopkeeper",
  "Nigerian Entrepreneur",
  "Kenyan Conservationist",
  "South African Businesswoman",
  "Indian Engineer",
  "Indian Entrepreneur",
  "Indian Grandmother",
  "Pakistani Doctor",
  "Bangladeshi Entrepreneur",
  "Chinese Businesswoman",
  "Chinese Engineer",
  "Japanese Salarywoman",
  "Japanese Craftsperson",
  "Korean Entrepreneur",
  "Korean Student",
  "Vietnamese Entrepreneur",
  "Filipino Nurse",
  "Indonesian Business Owner",
  "Australian Outback Farmer",
  "Māori Community Leader",
  "Indigenous Elder",
  "Jesus Christ",
  "Lucifer",
  "Christian Theologian",
  "Catholic Priest",
  "Catholic Nun",
  "Protestant Pastor",
  "Orthodox Monk",
  "Jewish Rabbi",
  "Muslim Imam",
  "Buddhist Monk",
  "Buddhist Nun",
  "Hindu Philosopher",
  "Taoist Sage",
  "Confucian Scholar",
  "Sufi Mystic",
  "Secular Humanist",
  "Atheist Philosopher",
  "Agnostic Skeptic",
  "Stoic Philosopher",
  "Epicurean",
  "Existentialist",
  "Medieval Knight",
  "Medieval Queen",
  "Renaissance Scholar",
  "Renaissance Merchant",
  "Victorian Lady",
  "Victorian Gentleman",
  "Enlightenment Philosopher",
  "1920s Flapper",
  "1950s Housewife",
  "1960s Hippie",
  "1980s Wall Street Trader",
  "1990s Hacker",
  "Cold War Spy",
  "Ancient Greek Philosopher",
  "Roman Senator",
  "Roman Matron",
  "Egyptian Priestess",
  "Samurai",
  "Geisha",
  "Viking Shieldmaiden",
  "Tribal Elder",
  "Revolutionary",
  "Dissident",
  "Vampire",
  "Sorceress",
  "Witch",
  "Wizard",
  "Necromancer",
  "Alchemist",
  "Oracle",
  "Fortune Teller",
  "Fairy",
  "Elf",
  "Demon",
  "Angel",
  "Fallen Angel",
  "Goddess",
  "Warrior Princess",
  "Dark Queen",
  "Forest Witch",
  "Cyberpunk Mercenary",
  "Space Captain",
  "Alien Anthropologist",
  "Time Traveler",
  "Immortal",
  "Artificial Superintelligence",
  "Barbie",
  "Femme Fatale",
  "Action Heroine",
  "Mad Scientist",
  "Supervillain",
  "Superhero",
  "Antihero",
  "Detective",
  "Noir Detective",
  "Mastermind",
  "Charming Villain",
  "Evil Genius",
  "Reluctant Hero",
  "Trickster",
  "Court Jester",
  "Happy",
  "Melancholic",
  "Angry",
  "Anxious",
  "Calm",
  "Enthusiastic",
  "Apathetic",
  "Bitter",
  "Hopeful",
  "Fearful",
  "Suspicious",
  "Paranoid",
  "Confident",
  "Insecure",
  "Arrogant",
  "Humble",
  "Compassionate",
  "Ruthless",
  "Forgiving",
  "Vindictive",
  "Pain and Suffering",
  "Dark Humor",
  "Deadpan",
  "Sarcastic",
  "Playful",
  "Hyper-Rational",
  "Bayesian Thinker",
  "Systems Thinker",
  "First-Principles Thinker",
  "Game Theorist",
  "Risk Analyst",
  "Probabilistic Thinker",
  "Long-Term Thinker",
  "Short-Term Opportunist",
  "Cost-Benefit Analyst",
  "Utilitarian",
  "Deontologist",
  "Consequentialist",
  "Machiavellian Strategist",
  "Red-Team Analyst",
  "Blue-Team Defender",
  "Socratic Questioner",
  "Scientific Skeptic",
  "Evidence Maximalist"
];
